"""Add zip_code to EventVenue model

Revision ID: 1615f3d9c77
Revises: 161e17ae42f8
Create Date: 2014-06-27 19:45:57.211021

"""

# revision identifiers, used by Alembic.
revision = '1615f3d9c77'
down_revision = '161e17ae42f8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_venue', sa.Column('zip_code', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event_venue', 'zip_code')
    ### end Alembic commands ###
