"""Added Geoname table

Revision ID: 213b69319410
Revises: ef4c018bec0
Create Date: 2014-06-15 11:54:06.679286

"""

# revision identifiers, used by Alembic.
revision = '213b69319410'
down_revision = 'ef4c018bec0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('geoname',
    sa.Column('geonameid', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('asciiname', sa.String(length=200), nullable=True),
    sa.Column('alternatenames', sa.String(length=8000), nullable=True),
    sa.Column('latitude', sa.Float(precision=10, asdecimal=6), nullable=True),
    sa.Column('longitude', sa.Float(precision=10, asdecimal=6), nullable=True),
    sa.Column('feature_class', sa.String(length=1), nullable=True),
    sa.Column('feature_code', sa.String(length=10), nullable=True),
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.Column('cc2', sa.String(length=60), nullable=True),
    sa.Column('admin1_code', sa.String(length=20), nullable=True),
    sa.Column('admin2_code', sa.String(length=80), nullable=True),
    sa.Column('admin3_code', sa.String(length=20), nullable=True),
    sa.Column('admin4_code', sa.String(length=20), nullable=True),
    sa.Column('population', sa.BigInteger(), nullable=True),
    sa.Column('elevation', sa.Integer(), nullable=True),
    sa.Column('dem', sa.Integer(), nullable=True),
    sa.Column('timezone', sa.String(length=40), nullable=True),
    sa.Column('modification_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('geonameid')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('geoname')
    ### end Alembic commands ###
