"""Store links to a user's avatar in the database

Revision ID: 22f0025beed3
Revises: 503331cbdff0
Create Date: 2014-07-05 15:59:50.510766

"""

# revision identifiers, used by Alembic.
revision = '22f0025beed3'
down_revision = '503331cbdff0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_large', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('avatar_small', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_small')
    op.drop_column('users', 'avatar_large')
    ### end Alembic commands ###
