"""Added indexes for commonly-used Geoname columns

Revision ID: 2ca57a3fe60b
Revises: 213b69319410
Create Date: 2014-06-15 16:57:53.970394

"""

# revision identifiers, used by Alembic.
revision = '2ca57a3fe60b'
down_revision = '213b69319410'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_geoname_country_code'), 'geoname', ['country_code'], unique=False)
    op.create_index(op.f('ix_geoname_feature_class'), 'geoname', ['feature_class'], unique=False)
    op.create_index(op.f('ix_geoname_feature_code'), 'geoname', ['feature_code'], unique=False)
    op.create_index(op.f('ix_geoname_name'), 'geoname', ['name'], unique=False)
    op.create_index(op.f('ix_geoname_population'), 'geoname', ['population'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_geoname_population'), table_name='geoname')
    op.drop_index(op.f('ix_geoname_name'), table_name='geoname')
    op.drop_index(op.f('ix_geoname_feature_code'), table_name='geoname')
    op.drop_index(op.f('ix_geoname_feature_class'), table_name='geoname')
    op.drop_index(op.f('ix_geoname_country_code'), table_name='geoname')
    ### end Alembic commands ###
