"""Add lat/long to EventVenue

Revision ID: 503331cbdff0
Revises: 1615f3d9c77
Create Date: 2014-06-29 13:52:01.969466

"""

# revision identifiers, used by Alembic.
revision = '503331cbdff0'
down_revision = '1615f3d9c77'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_venue', sa.Column('latitude', sa.Float(precision=10, asdecimal=6), nullable=True))
    op.add_column('event_venue', sa.Column('longitude', sa.Float(precision=10, asdecimal=6), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event_venue', 'longitude')
    op.drop_column('event_venue', 'latitude')
    ### end Alembic commands ###
