"""Added leagues model

Revision ID: ef4c018bec0
Revises: 162f5c76423f
Create Date: 2014-06-14 15:59:12.244865

"""

# revision identifiers, used by Alembic.
revision = 'ef4c018bec0'
down_revision = '162f5c76423f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('league',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tournament_url', sa.String(length=255), nullable=True),
    sa.Column('itemdef', sa.Integer(), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('image_url_large', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('league')
    ### end Alembic commands ###
